url: https://cahyohard9-maker.github.io
baseurl: /bigThinker/

# Site settings
title: Silica Gel Surabaya
email: desiccantosby@gmail.com
description: Kami melayani penjualan eceran maupun grosir produk silica gel dan desiccant silahkan klik desiccanto.com (B2B) atau desiccanto.shop (Retail)


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: DESICCANTO.COM
    url: https://www.desiccanto.com/
  - title: DESICCANTO.SHOP
    url: https://www.desiccanto.shop/
  - title: SILICAGEL.ID
    url: https://www.silicagel.id/
  
# Office address :
address:
  - line: Gunungsari Indah blok U No.5
  - line: Surabaya, Jawa Timur 60223

# Build settings
markdown: kramdown
permalink: silica gel surabaya
